packadd! dracula
syntax enable
colorscheme dracula

set linebreak	
set showbreak=+++
set textwidth=100
set showmatch	
set visualbell	
 
set hlsearch	
set number
set smartcase	
set incsearch	
 
set autoindent
set shiftwidth=4
set smartindent	
set smarttab
set softtabstop=4	
 
set ruler	 
 
set undolevels=1000	
set backspace=indent,eol,start
if has('mouse')
          set mouse=a
endif
